### ISSUE TITLE
句読点の改行位置がおかしい

### ISSUE THREAD

**Issue by kashewnuts** [vim-jp/autofmt#13]
環境:
- Windows 10 Professional 64bit
- GVim 8.0.0082 (Win32 kaoriya)
- autofmt(最新:2016/11/25版)

vimrc内の設定(関連個所
```
set formatexpr=autofmt#japanese#formatexpr()
let autofmt_allow_over_tw=1
```

上記再現手順後の関連オプション値
```
:set formatexpr?
  formatexpr=autofmt#japanese#formatexpr()
:set formatoptions?
  formatoptions=mMtcrql
:set encoding?
  encoding=utf-8
:set fenc?
  fileencoding=
```

どうやら「、」や「。」の後で改行してくれないように見えます。

期待値:
```
----+----1----+----2----+----3----+----4----+----5----+----6----+----7----+---|||+
あいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいう。
あいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいう、
あいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいうえ。
あいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいうえ、
あいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいうえ
お。
あいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいうえ
お、
```

実際:
```
----+----1----+----2----+----3----+----4----+----5----+----6----+----7----+---|||+
あいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいう。
あいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいう、
あいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいうえ
。
あいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいうえ
、
あいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいうえ
お。
あいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいうえ
お、
```

**Comment by h-east** [comment]
`autofmt`が正しく動作していないようです。
`autofmt`の最新版はもともとあった場所(C:\～\vim\plugin\autofmt)に上書きしました？
`set rtp?`の結果に`autofmt`へのパスは含まれているでしょうか？
GVimは64bit版でしょうか？

Kaoriya版であればコマンドプロンプトでvimインストールフォルダに`cd`して以下を実行すれば問題なく`gq`が動くはずです。
```dos
gvim -Nu NONE --cmd "set enc=utf-8 rtp+=plugins/autofmt" -c "set fex=autofmt#japanese#formatexpr() fo+=mB tw=78" -c "let autofmt_allow_over_tw=1"
```

**Comment by h-east** [comment]
あと念のためですが、https://github.com/vim-jp/autofmt/issues/1#issuecomment-14439634 のような環境になっていないか確認下さい。

**Comment by kashewnuts** [comment]
`autofmt`は最新版をもともとあった場所(C:\～\vim\plugin\autofmt)に上書きしました。

`gvim -Nu NONE --cmd "set enc=utf-8 rtp+=plugins/autofmt" -c "set fex=autofmt#japanese#formatexpr() fo+=mB tw=78" -c "let autofmt_allow_over_tw=1"` で確認したところ、以下のようになりました。(改行される位置がはやくなってる？)

```
あいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいう。
あいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいう、
あいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいう
え。
あいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいう
え、
あいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいうえ
お。
あいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいうえおあいうえ
お、
```

https://github.com/vim-jp/autofmt/issues/1#issuecomment-14439634 についても確認しましたが、自前ビルドはしていない上、`gvim.exe`も1つしかないので問題ないかと思います。

**Comment by h-east** [comment]
結果はそれであっています。(twの78 + autofmt_allow_over_twの1 == 79桁までOK。80桁に掛かる文字は改行される)
ですので @kashewnuts さんの設定がミスっていると思います。
`autofmt`がちゃんと動いていないので、おそらく、`rtp`を `=` で上書きしてしまっているとか？
自前設定のGVim起動時に以下を確認下さい。
> `set rtp?`の結果に`autofmt`へのパス`C:\～\vim\plugin\autofmt`は含まれているでしょうか？

**Comment by kashewnuts** [comment]
`set rtp?`の結果に`autofmt`のパスが含まれていなかったので、プラグインマネージャーで読み込んでいるプラグインをOFFにして`set runtimepath& runtimepath+=$VIM/plugins/autofmt`したところ期待する動作が確認できました。ありがとうございます！

**Comment by kashewnuts** [comment]
自分の設定ミスということがわかったので本件closeいたします。
