### ISSUE TITLE
ヘルプの例に間違いが有る

### ISSUE THREAD

**Issue by iranoan** [vim-jp/autofmt#20]
`:help autofmt-customize`

で見られるカスタマイズ例に

>   let s:unicode = unicode#import()

とありますが
`  let s:unicode = autofmt#unicode#import()`
の間違いですよね

**Comment by h-east** [comment]
@iranoan はい。間違いです。報告thanks:+1:

**Comment by iranoan** [comment]
確認+ブランチへの修正反映ありがとございます
