### ISSUE TITLE
カタカナの改行位置が不正

### ISSUE THREAD

**Issue by k-takata** [vim-jp/autofmt#5]
以下のファイルに対し、`tw=68` に設定し、2～6行目を1行ずつ整形してみます。(github上で見ると崩れていますが…。)

```
----+----1----+----2----+----3----+----4----+----5----+----6----+---|7||||+
１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１フォーマット
１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１フォーマト
１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１フーマト
１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１フォマト
１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１　フォマト
```

実行例:

```
vim -N -u NONE -U NONE --cmd "set rtp^=<autofmt-dir> tw=68" --cmd "set formatexpr=autofmt#japanese#formatexpr()" test.txt
```

`jgqq` を 5 回実行。

期待値:

```
----+----1----+----2----+----3----+----4----+----5----+----6----+---|7||||+
１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１フォー
マット
１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１フォー
マト
１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１フーマ
ト
１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１フォマ
ト
１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１　フォ
マト
```

実際:

```
----+----1----+----2----+----3----+----4----+----5----+----6----+---|7||||+
１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１
フォーマット
１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１
フォーマト
１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１フーマ
ト
１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１フォマ
ト
１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１　
フォマト
```

どうも、長音記号や拗音の後で改行してくれないようです。

**Comment by k-takata** [comment]
原因ですが、[Unicode 7.0対応](b51a318c71c6aab867f27535e9086be5f98f35bf)のときの不備ではないかと思います。
Unicode 6.1で、[UAX #14](http://unicode.org/reports/tr14/)が改定された際に、`CJ` (Conditional Japanese Starter)というプロパティーが追加されたのですが、それに対する処理が抜けているように思われます。
`CJ`は、strictな処理の場合は`NS`と同様に扱い、normalな処理の場合は`ID`と同様に扱う文字のようです。
> Treat as NS or ID for strict or normal breaking.

W3C の https://www.w3.org/TR/jlreq/ja/ によると、

```
3.9.2 文字・記号を振る舞い方により分ける

10. 長音記号（cl-10）
注2） JIS X 4051では，処理系定義として，長音記号[ー] (KATAKANA-HIRAGANA
PROLONGED SOUND MARK)を行頭禁則和字から除くことは認められている．

11. 小書きの仮名（cl-11）
注2） JIS X 4051では，処理系定義として，小書きの仮名（ぁぃぅァィゥなど）を行頭
禁則和字から除くことは認められている．
```

ということで、長音記号や拗音を、禁則処理の対象とするかどうかを選択できるようにするための処置のようです。
autofmtも、処理を選択できるようにしたほうが良いかもしれません。(現行はstrict相当のはず。)

**Comment by k-takata** [comment]
Fixed. Closing.

**Comment by koron** [comment]
ありがとうございます!

**Comment by koron** [comment]
対応するテストって、ありました?

**Comment by k-takata** [comment]
test3が日本語関連のテストですが、長音記号・拗音関連のテストはなかったですね。
あと、`autofmt_allow_over_tw`, `autofmt_allow_over_tw_char` と、今回追加した `autofmt_strict_japanese_linebreak` 関連のテストもありません。
